# Generated by Django 4.1.5 on 2023-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survivors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="resource",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="survivor",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
