# Generated by Django 4.1.5 on 2023-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survivors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survivor",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
